spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jdbctest?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    druid:
#    连接池建立时创建的初始化连接数
      initial-size: 5
#      连接池中最小的活跃连接数
      min-idle: 5
#      连接池中最大的活跃连接数
      max-active: 20
#      获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
#      用来检测连接是否有效的sql，要求是一个查询语句。
#      如果validationQuery为null，testOnBorrow、testOnReturn、
#      testWhileIdle都不会其作用
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      #      是否缓存preparedStatement，也就是PSCache。
      #       PSCache对支持游标的数据库性能提升巨大，比如说oracle。
      #       在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。
      #       5.5及以上版本有PSCache，建议开启。
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        stat:
          enabled: true
          merge-sql: true
          slow-sql-millis: 5000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        #\u8BBE\u7F6E\u4E0D\u7EDF\u8BA1\u54EA\u4E9BURL
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 100
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
# IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1
# IP黑名单 (存在共同时，deny优先于allow)
        #deny: 192.168.1.100
#配置视图前后缀
  mvc:
    view:
      prefix: /static/
      suffix: .html
      # \u9ED8\u8BA4\u503C\u4E3A /**
      #    static-path-pattern:
    static-path-pattern: /static/**
# 默认值为 /**
#    static-path-pattern:
# 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
